name: .NET Build

on: [push, pull_request]

# Move this workflow to a reusable workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore 
      
      - name: Test
        run: dotnet test --configuration Release --no-restore --no-build --verbosity normal
